name: gptme-bot

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # needed to run the action in the same repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gptme-bot action
        uses: ./.github/actions/bot
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowlist: "ErikBjare"
