name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    name: Test on ${{ matrix.os }}, py-${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    env:
      RELEASE: false
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.10']
        extras: ['browser']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install poetry
      run: |
        pip install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        make build
        poetry install -E "${{ matrix.extras }}"
    - name: Install dependencies for extras
      run: |
        if [ "${{ matrix.extras }}" = "browser" ]; then
          poetry run playwright install
        fi
    - name: Run tests
      env:
        TERM: xterm
      run: |
        make test SLOW=true
    - name: Typecheck
      run: |
        make typecheck
    - name: Check for lint
      run: |
        make lint
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
